PROCESSING_TIME_TRIGGER_TYPE = 'processingTime'
ONCE_TRIGGER_TYPE = 'once'
CONTINUOUS_TRIGGER_TYPE = 'continuous'
TRIGGER_TYPES = [PROCESSING_TIME_TRIGGER_TYPE, ONCE_TRIGGER_TYPE,
                 CONTINUOUS_TRIGGER_TYPE]
